language: generic

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE redmine_test;'

script:
  - docker build -t ppschweiz/redmine .
  - docker run --name redmine -d --rm --volume=/tmp/redmine:/home/redmine/data --env='DB_ADAPTER=mysql2' --env='DB_NAME=redmine_test' --env='DB_USER=travis' ppschweiz/redmine
  - docker ps | grep -q redmine
